#!/bin/bash
#
# Requires a mvn package to download the ASM and bundle JH dependencies!
#
# Set the JH as classloader and runs the main-Method of the given class.
#
# Usage: jhmain <main class> [arguments]
#

M2_REPO=~/.m2/repository

CLASSPATH=$CLASSPATH:target/classes
CLASSPATH=$CLASSPATH:target/test-classes
CLASSPATH=$CLASSPATH:target/java-hardener-0.1.0-SNAPSHOT.jar
CLASSPATH=$CLASSPATH:$M2_REPO/org/ow2/asm/asm/4.1/asm-4.1.jar
CLASSPATH=$CLASSPATH:$M2_REPO/org/ow2/asm/asm-util/4.1/asm-util-4.1.jar

java -cp $CLASSPATH de.fhkoeln.gm.cui.javahardener.JHMain $*
