#!/bin/bash
#
# Requires a mvn package to download the ASM dependencies!
#
# Usage: textifier <classfile>
#

M2_REPO=~/.m2/repository

CLASSPATH=$CLASSPATH:$M2_REPO/org/ow2/asm/asm/4.1/asm-4.1.jar
CLASSPATH=$CLASSPATH:$M2_REPO/org/ow2/asm/asm-util/4.1/asm-util-4.1.jar

java -cp $CLASSPATH org.objectweb.asm.util.Textifier $*
